// File generated by FlutterFire CLI.
// Run `flutterfire configure` to generate this file with your Firebase project settings.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these with your actual Firebase configuration
  // Run `flutterfire configure` to generate proper values

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaI0zP8c-jqawhxNfyCvYfjdltAMJCe8o',
    appId: '1:811664595416:web:6bd29bec55e1b54a543aad',
    messagingSenderId: '811664595416',
    projectId: 'calmwand-flutter-app',
    authDomain: 'calmwand-flutter-app.firebaseapp.com',
    storageBucket: 'calmwand-flutter-app.firebasestorage.app',
  );

  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDTSqKh2MDEBaBHaHGGBqLH1eiPgdczkc',
    appId: '1:811664595416:android:59f4948cb4fb9f11543aad',
    messagingSenderId: '811664595416',
    projectId: 'calmwand-flutter-app',
    storageBucket: 'calmwand-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkl-ZgN1kjQevl_tjjAfrFj1IF3pY2YRI',
    appId: '1:811664595416:ios:e8e275a1afd5e213543aad',
    messagingSenderId: '811664595416',
    projectId: 'calmwand-flutter-app',
    storageBucket: 'calmwand-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.calmwandFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.calmwandFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}